force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Markets</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservations</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reservation_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Total_Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Guests__c</fullName>
    <label>Total Number of Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ReservationManagerController.cls
public with sharing class ReservationManagerController {
	@auraEnabled
    public static List<CustomerServices.Customer> getCustomerList(String sObjectType)
    {
        List<CustomerServices.Customer> customers = new List<CustomerServices.Customer>();
        
        if(sObjectType == 'Lead')
        {
            for(Lead l:[SELECT Id, Email, Name, City, State, Status 
                        FROM Lead 
                        WHERE Status 
                        IN ('Open - Not Contacted') 
                        LIMIT 5])
            {
                CustomerServices.Customer c = new CustomerServices.Customer(l.Name, l.Email, l.City, l.State, l.Status,l.Id);
                customers.add(c);
            }
        }
                
        if(sObjectType == 'Contact')
        {
            for(Contact c:[SELECT Id, Email, Name, MailingCity, MailingState, Reservation_Status__c FROM Contact WHERE Reservation_Status__c IN ('Not Started') LIMIT 5])
            {
                CustomerServices.Customer cu = new CustomerServices.Customer(c.Name, c.Email, c.MailingCity, c.MailingState, c.Reservation_Status__c, c.Id);
                customers.add(cu);
            }
        }
        return customers;
    }

    @auraEnabled
    public static List<Reservation__c> getOpenReservations()
    {
        return [SELECT Id, Name, Contact__c, Contact__r.Name, Lead__c, Lead__r.Name, Market__c, Market__r.Name, Status__c, Start_Date__c, End_Date__c, Total_Number_of_Guests__c 
                FROM Reservation__c 
                WHERE Status__c IN ('Not Started', 'Draft') 
                LIMIT 10];
    }
}